name: CI Verify Dockerfile
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
jobs:
  verify-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile