name: CI Verify Docker
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
jobs:
  verify-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
      - name: Build the Docker image
        run: docker build .
